project-inclusive/OpenFisca-Japan

- dashboard/package-lock.json
- dashboard/package.json
- dashboard/src/components/form.tsx
- dashboard/src/hooks/calculate.ts
- この Pull request は バックエンドへのリクエストを必要数に絞ることでサーバー負荷を減らす
- そのために 「計算」ボタンを追加した
- 計算ボタンを押したタイミングで初めてリクエスト
- 「受けられる手当（月額）」にスクロール
Close #6
> Delay request

- openfisca_japan/parameters/福祉/生活福祉資金貸付制度/生活支援費_貸付額_二人以上.yaml
- openfisca_japan/parameters/福祉/生活福祉資金貸付制度/生活支援費_貸付額_単身.yaml
- openfisca_japan/variables/人口.py
- openfisca_japan/variables/所得.py
- openfisca_japan/variables/福祉/生活福祉資金貸付制度.py
- この Pull request は 生活福祉資金貸付制度の生活支援費という制度を追加する
> 生活福祉資金貸付制度の生活支援費を実装

- dashboard/package-lock.json
- dashboard/package.json
- dashboard/src/App.tsx
- dashboard/src/components/form.tsx
- dashboard/src/components/forms/attributes/Birthday.tsx
- dashboard/src/components/forms/attributes/validation/ErrorMessage.tsx
- dashboard/src/components/result.tsx
- dashboard/src/contexts/ShowAlertMessageContext.ts
- dashboard/src/hooks/validate.ts
- dashboard/src/pages/CaluculationForm.tsx
- dashboard/src/pages/Description.tsx
- この Pull request は dashboardのページを分割しルーティングを追加する
- そのために トップページ を追加した
- そのために フォーム入力欄と結果のページを分割した
- そのために フォームの必須項目チェックを追加した
close #13
> ページを分割しルーティング追加

- dashboard/src/App.tsx
- この Pull request は Github pagesのルートURLをreact routerに設定する
> Github pagesのルートURLをreact routerに設定

- dashboard/src/components/form.tsx
- dashboard/src/components/forms/you.tsx
- dashboard/src/pages/CaluculationForm.tsx
- この Pull request はAPIのURLの誤記を修正する。
> APIのURLの誤記を修正

- dashboard/src/app_config.json
- dashboard/src/components/form.tsx
- dashboard/src/components/forms/attributes/ChildrenNum.tsx
- dashboard/src/components/forms/attributes/Disability.tsx
- dashboard/src/components/result.tsx
- dashboard/src/contexts/AllowanceContext.ts
- dashboard/src/contexts/YourselfContext.ts
- dashboard/src/pages/CaluculationForm.tsx
- この Pull request は 定義ファイルからキャプションを読み込むよう修正する
> 定義ファイルからキャプションを読み込むよう修正

- dashboard/src/components/form.tsx
- この Pull request は APIロード中のスピナーを追加する
> APIロード中のスピナーを追加

- dashboard/src/components/forms/attributes/Income.tsx
- この Pull request は 年収入力フォームの入力確定時の挙動を修正する
- そのために Enterキー入力によるページ遷移を無効化した
- 備考
- 「こどもの数」ではEnterキー入力時に画面遷移はもともと発生しなかった
close #22
> フォーム入力確定時のページ遷移を無効化

- dashboard/src/App.tsx
- dashboard/vite.config.ts
- この Pull request は netlifyデプロイ用にbase URLを変更
> netlifyデプロイ用にbase URLを変更

- Doc/dev_note.md
- README.md
- dashboard/src/App.tsx
- dashboard/src/app_config.json
- dashboard/src/pages/CaluculationForm.tsx
- この Pull request は webアプリURLを変更する
> webアプリURLを変更

- openfisca_japan/variables/住居.py
- openfisca_japan/variables/所得.py
- openfisca_japan/variables/福祉/生活保護.py
- この Pull request は 生活保護の算出アウトラインを作成する
> 生活保護の算出アウトラインを作成

- dashboard/src/components/forms/attributes/HighSchool.tsx
- dashboard/src/components/forms/caluculationForm.tsx
- dashboard/src/components/forms/children.tsx
- dashboard/src/config/app_config.json
- この Pull request は 高等学校奨学給付金のフロントエンド を追加する
- そのために 高等学校奨学給付金 の支給額を追加した
- そのために こどもの高校種別 を追加した
> 高等学校奨学給付金のフロントエンド追加

- dashboard/src/components/forms/attributes/HighSchool.tsx
- この Pull request は [こちら](https://github.com/project-inclusive/OpenFisca-Japan/issues/126)のissue対応を行う。
- そのために 高校の種類に 「国立・公立・私立」を選択する項目を追加した
> 高等学校奨学給付金の私立高校の場合のFE実装

- .github/workflows/test_backend.yml
- .github/workflows/test_frontend.yml
- この Pull request は CIによるPR作成時自動テスト を追加する
- そのために バックエンドテストのGitHub Actions を追加した
- そのために フロントエンドテストのGitHub Actions を追加した
- fork先で実行されたactions
- backend: https://github.com/Syuparn/OpenFisca-Japan/actions/runs/6292942761
- frontend: https://github.com/Syuparn/OpenFisca-Japan/actions/runs/6292942763
close #128
> バックエンドテストのGitHub Actionsを追加

- openfisca_japan/variables/福祉/育児/高等学校等就学支援金.py
- この Pull request は高等学校等就学支援金制度 を追加する
- そのためにバックエンドのVariable 高等学校等就学支援 を追加した (仮実装)
- フロントエンド実装を並行して進められるようにするための仮実装なので、テストケースはこのPRでは追加していません
close #134
> 高等学校等就学支援金制度のバックエンド実装（Variable仮作成）

- .github/workflows/test_frontend.yml
- dashboard/package.json
- docs/dev_note.md
- This Pull request adds prettier check on github actions.
If there is better way to check pretty, please suggest.
> add prettier check action

- dashboard/index.html
- この Pull request は XXX を追加|改善|修正する
- そのために YYY を追加した
- そのために ZZZ を変更した
> Google analytics対応(トップページに来たときのみ集計)

- dashboard/src/components/forms/attributes/AgeInput.tsx
- dashboard/src/components/forms/attributes/ChildrenNum.tsx
- dashboard/src/components/forms/attributes/Income.tsx
- dashboard/src/components/forms/attributes/ParentsNum.tsx
- この Pull request は safariで数字入力フォームで数字以外入力できないようにする
> issue#24(safariで数字入力フォームで数字以外入力できないようにする)

- .prettierignore
- .prettierrc
- dashboard/.prettierignore
- dashboard/.prettierrc
Moving prettier file to top level so it can work on save
> Move prettier rc

- openfisca_japan/variables/住居.py
- openfisca_japan/variables/住民税.py
- openfisca_japan/variables/所得税.py
- openfisca_japan/variables/福祉/生活保護.py
- openfisca_japan/variables/福祉/育児/高等学校奨学給付金.py
- openfisca_japan/variables/福祉/育児/高等学校等就学支援金.py
- この Pull request は バックエンドのファイル読み込みロジック を修正する
- そのために ファイル読み込み処理 を関数化した
- 変数のスコープをせばめ、意図せぬ上書きを防ぐため
close #182
> csvファイル読み込みを関数化

- docs/dev_note.md
- この Pull request は `make build` 失敗した場合の対処方法を追加する
- そのために ドキュメント を追加した
> make build失敗する場合の対処を記載

- dashboard/src/components/result/benefit.tsx
- dashboard/src/components/result/loan.tsx
- dashboard/src/components/result/loanAccordion.tsx
- この Pull request は #222 を修正する
- そのために 外部リンクのtargetに_blankを指定して新しいタブで開くように修正した
> #222 詳細リンクのtargetに_blankを指定して新しいタブで開くようにした

- dashboard/cypress/e2e/DetailedCalculation.cy.js
- dashboard/cypress/e2e/Homepage.cy.js
- dashboard/cypress/e2e/SimpleCalculation.cy.js
- dashboard/src/App.tsx
- dashboard/src/components/Description.tsx
- dashboard/src/components/Terms.tsx
- dashboard/src/components/TermsModal.tsx
- dashboard/src/state.ts
- この Pull request は 利用規約に同意しないとサービス利用開始できないよう 修正する
- そのために 利用規約のモーダル を追加した
- そのために 見積もりボタンの表示条件 を変更した
> 利用規約のモーダルを追加

- requirements.txt
- setup.py
- この Pull request は バックエンドのモジュールのバージョン を更新する
- そのために setup.py を変更した
- そのために requirements.txt を変更した
- Dockerコンテナを再起動しUIから見積もりができることも確認
> バックエンドのバージョンを1.2.0へ更新

- .github/ISSUE_TEMPLATE.md
- .github/workflows/branch_restrictions.yml
- この Pull request はブランチ管理とissue templateを修正する
- そのために developブランチ以外からmainブランチへのマージを禁止するgithub actionsを追加
- そのために issue templateをわかりやすく修正した（参考：https://qiita.com/shunbaba/items/23c26d1800d879c33043）
> ブランチ管理とissue templateの修正

- docs/dev_note.md
mainブランチマージ前の作業を忘れないように開発ドキュメントに追記しました。  
他に追記事項等あれば、このブランチにプッシュしてもらって構いません。
- この Pull request は 開発ドキュメントにmainブランチマージ前のOpenFisca-Japanパッケージバージョン更新の備考追記する
> 開発ドキュメントにmainブランチマージ前のOpenFisca-Japanパッケージバージョン更新の備考追記

- dashboard/cypress/e2e/DetailedCalculation.cy.js
- dashboard/cypress/e2e/SimpleCalculation.cy.js
- dashboard/src/components/Description.tsx
- dashboard/src/components/TermsModal.tsx
- この Pull request は #237 を改善する
- そのために各ボタンに `data-testid` を追加した
> 要素のIDを指定せずにテストできるように修正

- dashboard/package-lock.json
- dashboard/package.json
- dashboard/src/components/result/result.tsx
- dashboard/src/components/result/shareLink.ts
- dashboard/src/config/app_config.json
- dashboard/src/hooks/calculate.ts
- dashboard/src/state.ts
- この Pull request は #68 を追加した
- そのために `shareLink.ts` を追加した
- そのためにパッケージ `pako` を追加した
> 結果画面の共有のための個別URLを作成できるようにした

- dashboard/src/components/forms/attributes/AgeInput.tsx
- dashboard/src/components/forms/attributes/SchoolYear.tsx
- dashboard/src/components/forms/children.tsx
- dashboard/src/components/forms/parents.tsx
- dashboard/src/components/forms/spouse.tsx
- dashboard/src/components/forms/you.tsx
- この Pull request は #257 修正する
- そのために [`SchoolYear.tsx`](https://github.com/project-inclusive/OpenFisca-Japan/compare/develop...minagishl:develop?expand=1#diff-f57760976e04af3e1354ed0e09e4e9064b9a8e93e48510e162a206120ff6d735) を追加した
- 以前の `<Birthday>...</Birthday>` はコメントアウトされています
> 生年月日から子供の学年を入力する様に変更

- docs/dev_note.md
- この Pull request は 当プロジェクトのソースコードのディレクトリ構成の説明 を追加する
- そのために フロントエンドのディレクトリ構成を追加した
- そのために バックエンドのディレクトリ構成を追加した
ドキュメントのみの修正のためテスト不要
close #270
> ディレクトリ構成の説明を追加

- dashboard/package-lock.json
- dashboard/package.json
- dashboard/src/components/forms/attributes/AgeInput.tsx
- dashboard/src/components/forms/attributes/ChildrenNum.tsx
- dashboard/src/components/forms/attributes/Deposit.tsx
- dashboard/src/components/forms/attributes/DisasterDeath.tsx
- dashboard/src/components/forms/attributes/Income.tsx
- dashboard/src/components/forms/attributes/ParentsNum.tsx
- dashboard/src/components/forms/attributes/SchoolYear.tsx
- dashboard/src/components/forms/you.tsx
- dashboard/src/utils/toHalf.ts
- この Pull request は #274 を修正した
- そのために `toHalf()` を追加した
- そのために インプットのタイプを number から text に変更した
- 数字以外入力できないように対策済み
> インプットなどに全角で入力した際に半角に変換するように改善

- dashboard/netlify.toml
- この Pull request は #300 に対応する
- そのために `netlify.toml` を追加した
（動作確認ができていないためチャックボックスを外しています）
> リダイレクト設定ファイルの追加

- dashboard/src/components/forms/attributes/IndustrialAccidentDisease.tsx
- dashboard/src/components/forms/attributes/IndustrialAccidentInjury.tsx
- dashboard/src/components/forms/attributes/Injury.tsx
- dashboard/src/components/forms/attributes/LeaveOfAbsense.tsx
- dashboard/src/components/forms/attributes/LeaveOfAbsenseByDisease.tsx
- dashboard/src/components/forms/attributes/LeaveOfAbsenseByInjury.tsx
- dashboard/src/components/forms/attributes/LeaveOfAbsenseWithoutSalary.tsx
- dashboard/src/components/forms/attributes/NewJob.tsx
- dashboard/src/components/forms/attributes/Occupation.tsx
- dashboard/src/components/forms/attributes/Recuperation.tsx
- dashboard/src/components/forms/parents.tsx
- dashboard/src/components/forms/spouse.tsx
- dashboard/src/components/forms/you.tsx
- dashboard/src/config/app_config.json
- dashboard/src/state.ts
- この Pull request は 傷病手当金 を追加する
- そのために フロントエンドのフォーム を追加した
> フロントエンドに傷病手当金を追加

- docs/dev_note.md
- この Pull request は 開発ドキュメント を追加する
- そのために 設計上のvaraibleの制約についての説明 を追加した
- そのために テスト生成方法の説明 を追加した
- ドキュメントのみの更新のため不要
> 開発ドキュメントを追加

- dashboard/src/config/app_config.json
- この Pull request は 先天性の...調査研究事業の窓口表示 を修正する
- そのために リンク を変更した
> 先天性の...調査研究事業のリンク修正

- dashboard/src/components/forms/attributes/Hemophilia/Hemophilia.tsx
- この Pull request は フロントエンドで血液凝固因子異常症のチェックを外した際見積もり結果でエラーが発生する不具合を修正する
- そのために YYY を追加した
- そのために 血液凝固因子異常症のフォーム を変更した
> 血液凝固因子異常症のチェックを外した際エラーが起こらないよう修正

- docs/dev_note.md
- この Pull request は リリース手順 を修正する
- そのために 開発者ドキュメントのリリース作業説明 を追加した
> リリース手順の内容を追記

- dashboard/src/components/result/result.tsx
- この Pull request は #335 を修正した
- そのために `見積もり結果` に置き換えた
> 見積もり結果で保存されるファイル名を変更

- dashboard/src/components/forms/attributes/AgeInput.tsx
- この Pull request は #324 を修正した
- そのために `handleAgeChange` を修正
- そのため [`49~52`](https://github.com/minagishl/OpenFisca-Japan/blob/506e75d7eb875cd5f4e16e2ea1ee1a95a95f7a6b/dashboard/src/components/forms/attributes/AgeInput.tsx#L48-L52) でそのまま値を設定する様にした
> 初期値の 0 を削除できる様に変更

- dashboard/src/components/forms/attributes/AgeInput.tsx
- dashboard/src/components/forms/attributes/ChildrenNum.tsx
- dashboard/src/components/forms/attributes/Deposit.tsx
- dashboard/src/components/forms/attributes/Income.tsx
- dashboard/src/components/forms/attributes/ParentsNum.tsx
- dashboard/src/components/forms/attributes/SchoolYear.tsx
- この Pull request は フォーム入力時に全角数字が複数回入力されてしまう不具合 を修正する
- そのために OS, ブラウザ判定 を追加した
- そのために Windows, Chromium系ブラウザの場合の数値更新処理 を変更した
Windows, Chrome
- 半角入力時
- 全角入力時
(Windows, Edgeも同様)
close #355
> Windows Chromeで全角入力が重複する不具合を修正

- dashboard/src/components/result/result.tsx
- dashboard/src/config/app_config.json
- この Pull request は 不具合報告用の環境情報取得ボタン を追加する
- そのために フロントエンドの見積もり結果に環境情報取得 を追加した
- 取得される文字列（JSON）
- ブラウザ、OS情報
```json
{"browser":{"name":"Chrome","version":"132.0.0.0","major":"132"},"os":{"name":"Windows","version":"10"}}
```
> 不具合報告用の環境情報取得ボタンを追加

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- この Pull request は issue_template を修正する
- そのために 古いテンプレートを削除した
- そのために 新しいバージョンに対応したテンプレートを追加した
テンプレートのみのためなし
close #374
> replace issue template with new format

- dashboard/src/App.tsx
- dashboard/src/components/forms/question.tsx
- dashboard/src/components/forms/templates/addressQuestion.tsx
- dashboard/src/components/forms/templates/ageQuestion.tsx
- dashboard/src/components/forms/templates/childAgeQuestion.tsx
- dashboard/src/components/forms/templates/incomeQuestion.tsx
- dashboard/src/components/forms/templates/personNumQuestion.tsx
- dashboard/src/components/forms/templates/selectionQuestion.tsx
- dashboard/src/components/forms/templates/yesNoQuestion.tsx
- dashboard/src/config/app_config.json
- developではなくUI開発用のブランチ `dev_new_gui` へ反映
- この Pull request は 新UIの一問一答フォーム画面 を追加する
- そのために フォームのテンプレート を追加した
- そのために テンプレート確認用に一時的に `/dummy/{テンプレート名}` でテンプレートが表示されるようにした
年齢
住所
2択
選択
収入
子どもの数
子どもの年齢
> 一問一答形式のフォームテンプレートを作成

- dashboard/src/components/forms/detailedQuestionList.tsx
- dashboard/src/components/forms/questions/childrenNumQuestion.tsx
- dashboard/src/components/forms/questions/deceasedNumberQuestion.tsx
- dashboard/src/components/forms/questions/disasterParentNumQuestion.tsx
- dashboard/src/components/forms/questions/parentNumQuestion.tsx
- dashboard/src/components/forms/questions/selfRentingHouse.tsx
- dashboard/src/components/forms/questions/simpleChildrenNumQuestion.tsx
- dashboard/src/components/forms/templates/personNumQuestion.tsx
- developではなくUI開発用のブランチdev_new_gui へ反映 
- この Pull request は 新UI「家を借りたいですか？」コンポーネント を追加する
- そのために SelfRentingHouse を追加した
※ Chromeブラウザ / iPhoneSEサイズで確認しました
> 新UI質問: 「家を借りたい」を実装する

- dashboard/src/components/forms/templates/childrenAgeQuestion.tsx
- この Pull request は 子どもの年齢のcomponent を修正する
- そのために useEffectによる更新 を変更した
- 年齢を固定したまま学年を1つ下げる
- 学年を固定したまま年齢を1つ下げる
> 子どもの年齢入力の不具合を修正
